# commands/help.py

async def execute(message, send_message):
    channel_id = message['channel_id']
    help_text = (
        "**Available commands:**\n"
        ";help - Shows this help message\n"
        ";r34 tag1 [tag2 tag3 ...] [amount=1] - Fetches images from Rule34 API\n"
        ";e621 tag1 [tag2 tag3 ...] [amount=1] - Fetches images from e621 API\n"
        ";tbib tag1 [tag2 tag3 ...] [amount=1] - Fetches images from TBIB API\n"
        ";atf tag1 [tag2 tag3 ...] [amount=1] - Fetches images from ATF API\n"
        ";Dragon (I don't know why I created this)\n"
        ";nsfw category [amount=1] - Fetches NSFW images from Night API\n"
        "   **Categories:**\n"
        "   - Anal\n"
        "   - Ass\n"
        "   - Boobs\n"
        "   - Gonewild\n"
        "   - Hanal\n"
        "   - Hass\n"
        "   - Hboobs\n"
        "   - Hentai\n"
        "   - Hkitsune\n"
        "   - Hmidriff\n"
        "   - Hneko\n"
        "   - Hthigh\n"
        "   - Neko\n"
        "   - Paizuri\n"
        "   - Pgif\n"
        "   - Pussy\n"
        "   - Tentacle\n"
        "   - Thigh\n"
        "   - Yaoi\n"
        "   - Random (fetches a random category)\n"
        ";pur category [amount=1] - Fetches images from Purrbot API\n"
        "   **Categories:**\n"
        "   - Angry\n"
        "   - Background\n"
        "   - Bite\n"
        "   - Blush\n"
        "   - Comfy\n"
        "   - Cry\n"
        "   - Cuddle\n"
        "   - Dance\n"
        "   - Eevee\n"
        "   - Fluff\n"
        "   - Holo\n"
        "   - Hug\n"
        "   - Icon\n"
        "   - Kiss\n"
        "   - Kitsune\n"
        "   - Lay\n"
        "   - Lick\n"
        "   - Neko\n"
        "   - Okami\n"
        "   - Pat\n"
        "   - Poke\n"
        "   - Pout\n"
        "   - Senko\n"
        "   - Shiro\n"
        "   - Slap\n"
        "   - Smile\n"
        "   - Tail\n"
        "   - Tickle\n"
    )
    await send_message(channel_id, help_text)
